DROP DATABASE KIDSBRASIL;


CREATE DATABASE KIDSBRASIL;


USE KIDSBRASIL;



CREATE TABLE PESSOA(
  IDPESSOA INT NOT NULL AUTO_INCREMENT ,
  
  TIPOPESSOA VARCHAR(45) NOT NULL ,
  NOME VARCHAR(45) NOT NULL ,
  SOBRENOME VARCHAR(45) NOT NULL ,
  DTNASC DATE NOT NULL ,
  EMAIL VARCHAR(45) NOT NULL ,
  SENHA VARCHAR(45) NOT NULL ,
  NWHATS VARCHAR(13) NOT NULL ,
  CPF VARCHAR(14) ,
  
  PRIMARY KEY(IDPESSOA)
);


CREATE TABLE ENDERECO(
  IDENDERECO INT NOT NULL AUTO_INCREMENT ,
  FKPESSOA INT NOT NULL ,

  CEP VARCHAR(9) NOT NULL ,
  RUA VARCHAR(45) NOT NULL ,
  N INT NOT NULL ,
  BAIRRO VARCHAR(45) NOT NULL ,
  CIDADE VARCHAR(13) NOT NULL ,
  ESTADO VARCHAR(4) NOT NULL ,
  OBS VARCHAR(45) NOT NULL ,
  
  PRIMARY KEY(IDENDERECO) ,
  FOREIGN KEY(FKPESSOA) REFERENCES PESSOA(IDPESSOA)
);



CREATE TABLE ESTADOVENDA(
  IDESTADOVENDA INT NOT NULL AUTO_INCREMENT ,

  NOMESTADOVENDA VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDESTADOVENDA)
);


CREATE TABLE MEIOPAGAMENTO(
  IDMEIOPAGAMENTO INT NOT NULL AUTO_INCREMENT ,

  NMEIOPGT VARCHAR(45) NOT NULL ,
  PARCELA INT NOT NULL ,

  PRIMARY KEY(IDMEIOPAGAMENTO)
);



CREATE TABLE DESC(
  IDDESC INT NOT NULL AUTO_INCREMENT ,

  NMDESC VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDDESC)
);


CREATE TABLE DESCVALOR(
  IDDESC INT NOT NULL AUTO_INCREMENT ,

  NMDESC VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDDESC)
);


CREATE TABLE VARIACAO(
  IDVARIACAO INT NOT NULL AUTO_INCREMENT ,

  NMVARIACAO VARCHAR(45) NOT NULL ,

  PRIMARY KEY(IDVARIACAO)
);



CREATE TABLE PRODUTO(
  IDPRODUTO INT NOT NULL AUTO_INCREMENT ,
  
  CODPRODUTO INT NOT NULL ,

  PRECO DECIMAL(10, 2) NOT NULL ,
  QTD INT NOT NULL ,
  URLPROD VARCHAR(45) NOT NULL ,
  SUBDESC VARCHAR(45) NOT NULL ,
  DESCPRODUTO VARCHAR(45) NOT NULL ,
  
  PRIMARY KEY(IDPRODUTO) 
);



CREATE TABLE VARIACAOPRODUTO(
  FKPRODUTO INT NOT NULL,
  FKVARIACAO INT NOT NULL,

  VALOR VARCHAR(45) NOT NULL ,
  PRECO DECIMAL(10, 2) NOT NULL ,
  
  FOREIGN KEY(FKPRODUTO) REFERENCES PRODUTO(IDPRODUTO) ,
  FOREIGN KEY(FKVARIACAO) REFERENCES VARIACAO(IDVARIACAO) 
);



CREATE TABLE VENDA(
  IDVENDA INT NOT NULL AUTO_INCREMENT ,
  FKMEIOPG INT,
  FKESTADOVENDA INT NOT NULL ,
  FKPESSOA INT NOT NULL ,
  FKENDERECO INT NOT NULL ,

  DTVENDA DATE NOT NULL ,
  
  PRIMARY KEY(IDVENDA) ,
  FOREIGN KEY(FKMEIOPG) REFERENCES MEIOPAGAMENTO(IDMEIOPAGAMENTO) ,
  FOREIGN KEY(FKESTADOVENDA) REFERENCES ESTADOVENDA(IDESTADOVENDA) ,
  FOREIGN KEY(FKPESSOA) REFERENCES PESSOA(IDPESSOA) ,
  FOREIGN KEY(FKENDERECO) REFERENCES ENDERECO(IDENDERECO)
);



CREATE TABLE ITEMVENDA(
  FKVENDA INT NOT NULL,
  FKPRODUTOV INT NOT NULL,
  FKVARIACAOV INT NOT NULL,

  QTDITEM INT NOT NULL ,

  FOREIGN KEY(FKVENDA) REFERENCES VENDA(IDVENDA) ,
  FOREIGN KEY(FKPRODUTOV) REFERENCES VARIACAOPRODUTO(FKPRODUTO) ,
  FOREIGN KEY(FKVARIACAOV) REFERENCES VARIACAOPRODUTO(FKVARIACAO) 
);







